# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53d10e7bfce5494cd14a2dc1451c4ae672b4a4e9c3397bbf08a8650ee49574f63525c9c3145218f025274085a978f5f4cb165bc9b64ccdf9c57f052124f6fc11

test:
  secret_key_base: dd097a319cd2042f1e9285b82c4c00856374849edce980e31f5c945f021f81fa7520031e673cd283187a6dcbd42a8422458494bc46613eb63d74a08d37f18aad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
