# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Commentaire.create({ comment:'This is #MAVOIX'})
Commentaire.create({ comment:'#MAVOIX compte'})
Commentaire.create({ comment:'Je récupère #MAVOIX'})
Commentaire.create({ comment:'Exprime ta voix avec #MAVOIX'})
Commentaire.create({ comment:'Tu veux donner de la voix ? Rejoins #MAVOIX'})
Commentaire.create({ comment:'Ça te dirait de faire entendre ta voix? #MAVOIX'})
Commentaire.create({ comment:'L\'intelligence collective c\'est notre voix, c\'est ta voix, c\'est #MAVOIX'})
Commentaire.create({ comment:'Le changement c\'est #MAVOIX !'})
Commentaire.create({ comment:'Participe au changement #MAVOIX'})
Commentaire.create({ comment:'Soyons acteurs de notre pays #MAVOIX'})
Commentaire.create({ comment:'Les règles datant du siècle passé, il est temps de les changer #MAVOIX'})
Commentaire.create({ comment:'Rejoins la révolution #MAVOIX'})
Commentaire.create({ comment:'Tous pourris? Viens expérimenter #MAVOIX'})
Commentaire.create({ comment:'Tu te sens impuissant? #MAVOIX'})
Commentaire.create({ comment:'#MAVOIX à l\'Assemblée Nationale !'})
Commentaire.create({ comment:'L\'intelligence collective enfin à l\'Assemblée Nationale! #MAVOIX'})
Commentaire.create({ comment:'Envie de hacker l\'Assemblée Nationale avec nous? #MAVOIX'})
Commentaire.create({ comment:'Toc Toc Toc, Viens à l\'Assemblée Nationale avec nous! #MAVOIX'})
Commentaire.create({ comment:'Bienvenue à la table des décisions #AssembléeNationale #MAVOIX'})
Commentaire.create({ comment:'Allons mettre du poil à gratter à l\'Assemblée Nationale #MAVOIX'})
Commentaire.create({ comment:'Nous allons entrer à l\'Assemblée Nationale en juin 2017! #MAVOIX'})
Commentaire.create({ comment:'Il paraît que je peux faire entendre #MAVOIX à mon député'})
Commentaire.create({ comment:'Le député peut être citoyen, le citoyen peut être député #MAVOIX'})
Commentaire.create({ comment:'Tous les citoyens peuvent se porter candidat à être député #MAVOIX'})
Commentaire.create({ comment:'Notre député sera le prolongement de notre volonté individuelle #MAVOIX'})
Commentaire.create({ comment:'Nous allons essayer la démocratie #MAVOIX'})
Commentaire.create({ comment:'Nous sommes de ceux qui n\'arrivent plus a aller voter la tête haute #MAVOIX'})
Commentaire.create({ comment:'Nous sommes celles et ceux que nous attendions #MAVOIX'})
Commentaire.create({ comment:'Nous sommes tous différents et nous ne sommes pas tous d\'accord #MAVOIX'})
Commentaire.create({ comment:'Je suis tombée là-dessus, tu connais #MAVOIX?'})
Commentaire.create({ comment:'Tu connais #MAVOIX ?'})
